title: Unofficial Sensei the MWZ Operator Remasters
description: Unofficial remasters of AdLad114514's Blue Archive fanfic series, Sensei the MWZ Operator into HTML/CSS.
remote_theme: underset/primer@testing

plugins:
- jekyll-remote-theme